#docker-compose.yml
version: "3.5"


services:
  postgres_db:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5434:5432"
    volumes: [ './postgres/db/:/var/lib/postgresql/data/', './postgres/db/:/logs/' ]
    command: ["postgres", "-c", "log_statement=all"]
    expose:
      - 5432
    networks:
      rent_vps_network:
        ipv4_address: 192.168.55.4

  django:
    depends_on:
      - postgres_db
    build: .
    container_name: django
    command: bash -c "
      python manage.py migrate
      && gunicorn rent_vps.wsgi:application --bind "0.0.0.0:8080" --workers 3
      "
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      rent_vps_network:
        ipv4_address: 192.168.55.5

networks:
  rent_vps_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.55.0/24
          gateway: 192.168.55.1
