# Generated by Django 5.1.5 on 2025-01-19 22:00

import django.core.validators
import vps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VPS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(db_index=True, max_length=50, unique=True)),
                (
                    "cpu",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(32),
                        ],
                    ),
                ),
                (
                    "ram",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(32),
                        ],
                    ),
                ),
                (
                    "hdd",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2000),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "STARTED"),
                            ("blocked", "BLOCKED"),
                            ("stopped", "STOPPED"),
                        ],
                        default="started",
                        max_length=7,
                        validators=[vps.models.validator_statuses],
                    ),
                ),
            ],
            options={
                "verbose_name": "VPS",
                "verbose_name_plural": "VPS",
                "ordering": ("id",),
            },
        ),
    ]
